/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.Scanner;

import java.io.File;
import java.io.FileNotFoundException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */

@SuppressWarnings( "serial" )
public class PersonalInfo extends javax.swing.JFrame {

    String name;
    
    /**
     * Creates new form PersonalInfo
     */
    public PersonalInfo( String n )
    {
        try{
            name = textReader();
        }
        catch(FileNotFoundException e){
            System.out.println("1");
        }
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButton7 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jRadioButton7.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton7.setText("Male");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 245, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("PERSONAL INFORMATION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 159;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 53, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setText("HEIGHT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 45, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText("WEIGHT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 45, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setText("GENDER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 45, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("AGE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 45, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 8, 0, 0);
        jPanel1.add(jTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        jPanel1.add(jTextField2, gridBagConstraints);

        jRadioButton1.setBackground(new java.awt.Color(235, 245, 253));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton1.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 8, 0, 0);
        jPanel1.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton2.setText("Gain Weight");
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 70;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 55;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        jPanel1.add(jRadioButton2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 0, 0);
        jPanel1.add(jTextField3, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 69;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 151;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 2, 0, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setText("ILLNESS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 10, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jRadioButton3.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton3.setText("Ulcer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 35;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(jRadioButton3, gridBagConstraints);

        jRadioButton4.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton4.setText("Diabetes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(jRadioButton4, gridBagConstraints);

        jRadioButton5.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton5.setText("Cirrhosis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 35;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        jPanel1.add(jRadioButton5, gridBagConstraints);

        jRadioButton6.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton6.setText("Gout");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 0, 0);
        jPanel1.add(jRadioButton6, gridBagConstraints);

        jRadioButton8.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton8.setText("Obesity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(jRadioButton8, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setText("WEIGHT GOAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 70;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 18, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 151;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 2, 0, 0);
        jPanel1.add(jSeparator2, gridBagConstraints);

        jRadioButton9.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton9.setText("Lose Weight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 70;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        jPanel1.add(jRadioButton9, gridBagConstraints);

        jRadioButton10.setBackground(new java.awt.Color(235, 245, 253));
        jRadioButton10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton10.setText("Maintain Weight");
        
        jButton10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                    String driver = "com.mysql.cj.jdbc.Driver";
                    String username = "root";
                    String password = "20210406cp";
                    
                   
                        String newHeight = jTextField1.getText();
                        String newWeight = jTextField2.getText();
                        String newAge = jTextField3.getText();
                        
                        String newGender = "";
                        if( jRadioButton1.isSelected() ) { newGender = jRadioButton1.getText(); }
                        else if( jRadioButton11.isSelected() ) { newGender = jRadioButton11.getText(); }
                        
                        String newGoal = "";
                        if( jRadioButton2.isSelected() ) { newGoal = jRadioButton2.getText(); }
                        else if( jRadioButton10.isSelected() ) { newGoal = jRadioButton10.getText(); }
                        else if( jRadioButton9.isSelected() ) { newGoal = jRadioButton9.getText(); }
                        
                        int uDiabet = 0;
                        if( jRadioButton4.isSelected() ) { uDiabet = 1; }
                        else{ uDiabet = 0; }
                        
                        int uGout = 0;
                        if( jRadioButton6.isSelected() ) { uGout = 1; }
                        else{ uGout = 0; }
                        
                        int uUlcer = 0;
                        if( jRadioButton3.isSelected() ) { uUlcer = 1; }
                        else{ uUlcer = 0; }
                        
                        int uObesity = 0;
                        if( jRadioButton8.isSelected() ) { uObesity = 1; }
                        else{ uObesity = 0; }
                        
                        int uCirrhosis = 0;
                        if( jRadioButton5.isSelected() ) { uCirrhosis = 1; }
                        else{ uCirrhosis = 0; }
                        
                        
                        try
                        {
                            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
                            Class.forName(driver);
                            java.sql.Connection conn2 = DriverManager.getConnection( url, username, password );
                            Statement statement = ((java.sql.Connection) conn2).createStatement();
                            String sql = "UPDATE user SET height = '" + newHeight + "', weight = '" + newWeight + "', age = '" + newAge + "', " + 
                            "gender = '" + newGender + "', goal = '" + newGoal + "', diabet = " + uDiabet + ", gout = " + uGout + 
                            ", ulcer = " + uUlcer + ", obesity = " + uObesity + ", cirrhosis = " + uCirrhosis + " WHERE username = '" + name + "'";
                            statement.executeUpdate(sql);
                            
                            statement.close();
                            conn2.close();
                             
                        } 
                        catch (ClassNotFoundException e)
                        {
                            e.printStackTrace();
                        } catch (SQLException e)
                        {
                            e.printStackTrace();
                        }
                        
                        // if( jTextField1.getText() == null || jTextField2.getText() == null || jTextField3.getText() == null ||
                        // ( !jRadioButton1.isSelected() && !jRadioButton11.isSelected() ) || 
                        // ( !jRadioButton2.isSelected() && !jRadioButton9.isSelected()  && !jRadioButton10.isSelected() ) )
                        // {
                        //     JFrame f = new JFrame();
                        //     JOptionPane.showMessageDialog( f, "Please be sure that\nthere is no missing part" );
                        // }
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 70;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 74;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        jPanel1.add(jRadioButton10, gridBagConstraints);

        jRadioButton11.setBackground(new java.awt.Color(235, 245, 253));
        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton11.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel1.add(jRadioButton11, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(253, 224, 224));
        jButton1.setText("Main Page");
        
        
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setText("EnergyTracker");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 0, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        jButton3.setText("Activity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        jPanel1.add(jButton3, gridBagConstraints);

        jButton4.setText("Food");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 0, 0);
        jPanel1.add(jButton4, gridBagConstraints);

        jButton5.setText("Water");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        jPanel1.add(jButton5, gridBagConstraints);

        jButton6.setText("History");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 52;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 0, 0);
        jPanel1.add(jButton6, gridBagConstraints);

        jButton7.setText("Settings");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 89;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 75;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 0, 0);
        jPanel1.add(jButton7, gridBagConstraints);

        jButton8.setText("Personal Info");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 164;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 160;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 0, 0);
        jPanel1.add(jButton8, gridBagConstraints);

        jButton9.setText("Feedback");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 324;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 0, 0);
        jPanel1.add(jButton9, gridBagConstraints);

        jButton10.setText("Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 12, 17, 0);
        jPanel1.add(jButton10, gridBagConstraints);
        
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPageGui main = new MainPageGui();
                main.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalorieFrame e = new CalorieFrame(name);
                e.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivityFrame2 a = new ActivityFrame2(name);
                a.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodSelectionGui f = new FoodSelectionGui();
                f.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterIntake w = new WaterIntake(name);
                w.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                History2frame h = new History2frame();
                h.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Settings s = new Settings();
                s.setVisible(true);
                setVisible(false);
            }
        });
        
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(true);
            }
        });
        
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback f = new feedback();
                f.setVisible(true);
                setVisible(false);
            }
        });
        
        String height ="";    
        try
            {
                String driver = "com.mysql.cj.jdbc.Driver";
                String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
                String username = "root";
                String password = "20210406cp";
                Class.forName(driver);
                java.sql.Connection conn = DriverManager.getConnection( url, username, password );
                Statement statement = conn.createStatement();
                String sql = "SELECT height FROM user WHERE username = '" + name + "'";
                ResultSet r = statement.executeQuery(sql);
                
                while( r.next() )
                {
                    height = r.getString( "height" );
                }
            } catch( Exception e ) { e.printStackTrace();}
        
        jTextField1.setText( height );
        
        String weight ="";    
        try
            {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT weight FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                weight = r.getString( "weight" );
            }
        } catch( Exception e ) { e.printStackTrace();}
        
        jTextField2.setText( weight );
        
        String age ="";    
        try
            {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT age FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                age = r.getString( "age" );
            }
        } catch( Exception e ) { e.printStackTrace();}
        
        jTextField3.setText( age );
        
        String gender = "";    
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT gender FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                gender = r.getString( "gender" );
            }
            
            if( gender.equals( "Female" ) )
            {
                jRadioButton1.setSelected(true);
            }
            
            else if( gender.equals( "Male" ) )
            {
                jRadioButton11.setSelected(true);
            }
            
        } catch( Exception e ) { e.printStackTrace();}
        
        String goal = "";    
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT goal FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                goal = r.getString( "goal" );
            }
            
            if( goal.equals( "Gain weight" ) )
            {
                jRadioButton2.setSelected(true);
            }
            
            else if( goal.equals( "Maintain weight" ) )
            {
                jRadioButton10.setSelected(true);
            }
            
            else if( goal.equals( "Lose weight" ) )
            {
                jRadioButton9.setSelected(true);
            }
            
        } catch( Exception e ) { e.printStackTrace();}
        
        int diabet = 0;
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT diabet FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                diabet = Integer.parseInt(r.getString( "diabet" ) );
            }
            
            if( diabet == 1 )
            {
                jRadioButton4.setSelected(true);
            }
        
        } catch( Exception e ) { e.printStackTrace();}
        
        int gout = 0;
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT gout FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                gout = Integer.parseInt(r.getString( "gout" ) );
            }
            
            if( gout == 1 )
            {
                jRadioButton6.setSelected(true);
            }
        
        } catch( Exception e ) { e.printStackTrace();}
        
        int ulcer = 0;
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT ulcer FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                ulcer = Integer.parseInt(r.getString( "ulcer" ) );
            }
            
            if( ulcer == 1 )
            {
                jRadioButton3.setSelected(true);
            }
        
        } catch( Exception e ) { e.printStackTrace();}
        
        int obesity = 0;
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT obesity FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                obesity = Integer.parseInt( r.getString( "obesity" ) );
            }
            
            if( obesity == 1 )
            {
                jRadioButton8.setSelected(true);
            }
        
        } catch( Exception e ) { e.printStackTrace();}
        
        int cirrhosis = 0;
        try
        {
            String driver = "com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
            String username = "root";
            String password = "20210406cp";
            Class.forName(driver);
            java.sql.Connection conn = DriverManager.getConnection( url, username, password );
            Statement statement = conn.createStatement();
            String sql = "SELECT cirrhosis FROM user WHERE username = '" + name + "'";
            ResultSet r = statement.executeQuery(sql);
                
            while( r.next() )
            {
                cirrhosis = Integer.parseInt(r.getString( "cirrhosis" ) );
            }
            
            if( cirrhosis == 1 )
            {
                jRadioButton5.setSelected(true);
            }
        
        } catch( Exception e ) { e.printStackTrace();}

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                try {
                    PersonalInfo s;
                    s = new PersonalInfo( textReader() );
                    s.setVisible(true);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });
    }
    
    public static String textReader() throws FileNotFoundException
    {
        File file = new File( "filename.txt" );
        Scanner scan = new Scanner( file );
        String name = scan.next();
        scan.close();
        return name;
    }  

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
}