/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.Date;
import java.text.*;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import javax.swing.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author yamac
 */
public class WaterIntake extends JFrame {
    static DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    
    public final static Instant today = Instant.now();
    public final static Instant oneDayAgo = today.minus(1, ChronoUnit.DAYS);
    public final static Instant twoDayAgo = today.minus(2, ChronoUnit.DAYS);
    
    public final static String todayString = dateFormat.format(Date.from(today));
    public final static String oneString = dateFormat.format(Date.from(oneDayAgo));
    public final static String twoString = dateFormat.format(Date.from(twoDayAgo));
    
    String user6;
    int todayProgress;
    /**
     * Creates new form WaterIntakeFrame
     */
    public WaterIntake(String user) {
        try
        {
            user6 = textReader();
        }
        catch(FileNotFoundException e){
            System.out.println("1");
        }
        initComponents();
        jProgressBar1.setMaximum(2500); 
        jProgressBar1.setMinimum(0);
        jProgressBar3.setMaximum(2500); 
        jProgressBar3.setMinimum(0);
        jProgressBar2.setMaximum(2500); 
        jProgressBar2.setMinimum(0);
          int oneDayProgres = 0;
            int twoDayProgres = 0;
            
        try{
            
            Class.forName( "com.mysql.jdbc.Driver" );
            Connection connect = DriverManager.getConnection(
                    "jdbc:mysql://34.69.74.87:3306/" +user6 , "root", "20210406cp" );

            Statement statement = connect.createStatement();
           ResultSet resultset=statement.executeQuery("SELECT * FROM water"  ) ;
            while (resultset.next()) {
                if(resultset.getString("date").equals(oneString)){
                     oneDayProgres += Integer.parseInt(resultset.getString("amount"));
                }
                if(resultset.getString("date").equals(twoString)){
                     twoDayProgres += Integer.parseInt(resultset.getString("amount"));
                }
                 if(resultset.getString("date").equals(todayString)){
                     todayProgress += Integer.parseInt(resultset.getString("amount"));
                }
            }
                    jProgressBar1.setValue(todayProgress);
                    jProgressBar2.setValue(oneDayProgres);
                    jProgressBar3.setValue(twoDayProgres);
            
            connect.close();  
        }
        catch( Exception e ) {
            System.out.println( e ) ;
            
        }
          waterAmount.setText(todayProgress+ " ml");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        welcomeLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        waterAmount = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        dateText = new javax.swing.JTextField();
        mainButton = new javax.swing.JButton();
        energyButton = new javax.swing.JButton();
        activityButton = new javax.swing.JButton();
        foodButton = new javax.swing.JButton();
        waterButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        personalButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(208, 240, 207));

        welcomeLogo.setBackground(new java.awt.Color(208, 240, 207));
        welcomeLogo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WATER INTAKE");
        welcomeLogo.add(jLabel1);
        jLabel1.setBounds(370, 40, 201, 29);

        jTextField1.setText("(ml)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        welcomeLogo.add(jTextField1);
        jTextField1.setBounds(120, 260, 99, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("AMOUNT");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pres Enter", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        welcomeLogo.add(jLabel2);
        jLabel2.setBounds(0, 244, 240, 60);

        jButton1.setText("Glass(200ml)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        welcomeLogo.add(jButton1);
        jButton1.setBounds(10, 200, 110, 23);

        jButton2.setText("Bottle(500ml)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        welcomeLogo.add(jButton2);
        jButton2.setBounds(130, 200, 110, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Yesterday");
        welcomeLogo.add(jLabel4);
        jLabel4.setBounds(630, 210, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("History");
        welcomeLogo.add(jLabel5);
        jLabel5.setBounds(730, 120, 92, 34);

        jProgressBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        welcomeLogo.add(jProgressBar1);
        jProgressBar1.setBounds(720, 190, 146, 11);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Today");
        welcomeLogo.add(jLabel6);
        jLabel6.setBounds(640, 180, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("2 Days ago");
        welcomeLogo.add(jLabel7);
        jLabel7.setBounds(630, 240, 80, 30);

        jProgressBar3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        welcomeLogo.add(jProgressBar3);
        jProgressBar3.setBounds(720, 250, 146, 11);

        jProgressBar2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        welcomeLogo.add(jProgressBar2);
        jProgressBar2.setBounds(720, 220, 146, 10);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        welcomeLogo.add(jButton3);
        jButton3.setBounds(823, 430, 90, 23);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        welcomeLogo.add(jTextField2);
        jTextField2.setBounds(830, 390, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Update goal");
        welcomeLogo.add(jLabel3);
        jLabel3.setBounds(820, 360, 90, 17);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        welcomeLogo.add(jSeparator1);
        jSeparator1.setBounds(710, 110, 310, 200);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("your water intake");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        welcomeLogo.add(jLabel8);
        jLabel8.setBounds(0, 390, 240, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Recomended goal");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        welcomeLogo.add(jLabel9);
        jLabel9.setBounds(0, 450, 250, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Log new intake");
        welcomeLogo.add(jLabel10);
        jLabel10.setBounds(60, 130, 120, 29);
        welcomeLogo.add(jLabel11);
        jLabel11.setBounds(0, 0, 0, 0);

        waterAmount.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        waterAmount.setText("Goal");
        welcomeLogo.add(waterAmount);
        waterAmount.setBounds(180, 390, 59, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("2500");
        welcomeLogo.add(jLabel13);
        jLabel13.setBounds(160, 450, 40, 20);

        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daily Goal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        welcomeLogo.add(jSeparator2);
        jSeparator2.setBounds(800, 330, 130, 150);

        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        welcomeLogo.add(jSeparator6);
        jSeparator6.setBounds(0, 100, 250, 230);

        dateText.setText("please enter date");
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });
        welcomeLogo.add(dateText);
        dateText.setBounds(270, 230, 120, 30);

        mainButton.setText("MAIN PAGE");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(mainButton);
        mainButton.setBounds(3, 10, 100, 23);

        energyButton.setText("ENERGY TRACKER");
        energyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(energyButton);
        energyButton.setBounds(100, 10, 140, 23);

        activityButton.setText("ACTIVITIY");
        activityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(activityButton);
        activityButton.setBounds(240, 10, 110, 23);

        foodButton.setText("FOOD");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(foodButton);
        foodButton.setBounds(350, 10, 90, 23);

        waterButton.setText("WATER INTAKE");
        waterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(waterButton);
        waterButton.setBounds(440, 10, 130, 23);

        historyButton.setText("HISTORY");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(historyButton);
        historyButton.setBounds(570, 10, 110, 23);

        personalButton.setText("PERSONAL INFO");
        personalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(personalButton);
        personalButton.setBounds(673, 10, 130, 23);

        settingsButton.setText("SETTINGS");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(settingsButton);
        settingsButton.setBounds(800, 10, 110, 23);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        welcomeLogo.add(backButton);
        backButton.setBounds(909, 10, 80, 23);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        todayProgress += 200; 
         
          int tmp = 200;
        jProgressBar1.setValue(todayProgress); 
             try{
            
            Class.forName( "com.mysql.jdbc.Driver" );
            Connection connect = DriverManager.getConnection(
                    "jdbc:mysql://34.69.74.87:3306/" +user6 , "root", "20210406cp" );

            Statement statement1 = connect.createStatement();
           // ResultSet resultset1 = statement1.executeQuery("SELECT date,time,amount FROM "+user +".water" );
               
           
            
            PreparedStatement statement = connect.prepareStatement("insert into "+user6+".water values (?, ?, ?)");
                 
            statement.setString(1, dateText.getText());
            statement.setString(2,"" );
            statement.setString(3, tmp+"");
        
            statement.executeUpdate();
            
            
            
            connect.close();
            
            
        }
        catch( Exception e ) {
            System.out.println( e ) ;
            
        }
       waterAmount.setText(todayProgress+ " ml");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jProgressBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1AncestorAdded

    private void jProgressBar3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar3AncestorAdded

    private void jProgressBar2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar2AncestorAdded

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel13.setText(jTextField2.getText()+ "  ml"); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        todayProgress += Integer.parseInt(jTextField1.getText() );
         
          int tmp = 200;
        jProgressBar1.setValue(todayProgress);
              try{
            
            Class.forName( "com.mysql.jdbc.Driver" );
            Connection connect = DriverManager.getConnection(
                    "jdbc:mysql://34.69.74.87:3306/" + user6 , "root", "20210406cp" );

            Statement statement1 = connect.createStatement();
           // ResultSet resultset1 = statement1.executeQuery("SELECT date,time,amount FROM "+user +".water" );
               
           
            
            PreparedStatement statement = connect.prepareStatement("insert into "+user6+".water values (?, ?, ?)");
                 
            statement.setString(1, dateText.getText());
            statement.setString(2,"" );
            statement.setString(3, tmp+"");
        
            statement.executeUpdate();
            
            
            
            connect.close();
            
            
        }
        catch( Exception e ) {
            System.out.println( e ) ;
            
        }
       waterAmount.setText(todayProgress+ " ml");
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        todayProgress+= 500 ; 
        int tmp = 500;
        jProgressBar1.setValue(todayProgress); 
        try{
            
            Class.forName( "com.mysql.jdbc.Driver" );
            Connection connect = DriverManager.getConnection(
                    "jdbc:mysql://34.69.74.87:3306/" +user6 , "root", "20210406cp" );

            Statement statement1 = connect.createStatement();
           // ResultSet resultset1 = statement1.executeQuery("SELECT date,time,amount FROM "+user +".water" );
               
           
            
            PreparedStatement statement = connect.prepareStatement("insert into "+user6+".water values (?, ?, ?)");
                 
            statement.setString(1, dateText.getText());
            statement.setString(2,"" );
            statement.setString(3, tmp+"");
        
            statement.executeUpdate();
            
            
            
            connect.close();
            
            
        }
        catch( Exception e ) {
            System.out.println( e ) ;
            
        }
        waterAmount.setText(todayProgress+ " ml"); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        MainPageGui main = new MainPageGui();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mainButtonActionPerformed

    private void energyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyButtonActionPerformed
        CalorieFrame frame = new CalorieFrame(user6);
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_energyButtonActionPerformed

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        ActivityFrame2 frame2 = new ActivityFrame2(user6);
        frame2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_activityButtonActionPerformed

    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButtonActionPerformed
       FoodSelectionGui selection = new FoodSelectionGui();
       selection.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_foodButtonActionPerformed

    private void waterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterButtonActionPerformed
        WaterIntake intake = new WaterIntake(user6);
        intake.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_waterButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        History2frame hist = new History2frame();
        hist.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_historyButtonActionPerformed

    private void personalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalButtonActionPerformed
        PersonalInfo info = new PersonalInfo(user6);
        info.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_personalButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        Settings set  = new Settings();
        set.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        feedback feed = new feedback();
        feed.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
        
    int prog1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activityButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton energyButton;
    private javax.swing.JButton foodButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton mainButton;
    private javax.swing.JButton personalButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel waterAmount;
    private javax.swing.JButton waterButton;
    private javax.swing.JPanel welcomeLogo;
    // End of variables declaration//GEN-END:variables
    public static String textReader() throws FileNotFoundException
    {
        File file = new File( "filename.txt" );
        Scanner scan = new Scanner( file );
        String name = scan.next();
        //String userPassword = scan.next();
        scan.close();
        return name;
    }
}
