/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.image.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Message;
import javax.mail.MessagingException;

/**
 *
 * @author pc
 */
@SuppressWarnings("serial")
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form UserGUI
     * @throws IOException
     */
    public WelcomePage() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws IOException
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws IOException {

        image = ImageIO.read( new File( "icon.png" ));
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel( new ImageIcon( image ));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTextField3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField3.setText("E-mail");

        jTextField4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField4.setText("Password");

        jButton2.setText("Login");

        jTextField5.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField5.setText("Name");

        jTextField6.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField6.setText("E-mail Address");

        jTextField7.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField7.setText("Password");

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Welcome To");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("For a personalized experience,   ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("create your HealMeal account and attain your goal!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setText("or");

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel5.setText("Start a New Journey");

        jTextField9.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextField9.setText("Confirm Password");

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel6.setText("Continue Your Experience");
        
        jButton2.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed( java.awt.event.ActionEvent evt )
            {
                String name = jTextField3.getText();
                String userPassword = jTextField4.getText();
                
                if( evt.getSource() == jButton2 )
                {
                    try
                    {
                        String driver = "com.mysql.cj.jdbc.Driver";
                        String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
                        String username = "root";
                        String password = "20210406cp";
                        Class.forName(driver);
                        java.sql.Connection conn = DriverManager.getConnection( url, username, password );
                  
                        Statement statement1=((java.sql.Connection) conn).createStatement();  
                        Statement statement2=((java.sql.Connection) conn).createStatement();  
                        ResultSet resultset1=statement1.executeQuery( "SELECT * FROM user WHERE username = '" + name + "'");
                        ResultSet resultset2 = statement2.executeQuery( "SELECT * FROM user WHERE password = '" + userPassword + "'" );
                        
                        if ( resultset1.next() && resultset2.next() )
                        {
                            MainPageGui main = new MainPageGui();
                            main.setVisible(true);
                            setVisible(false);
                            
                            // try
                            // {
                            //     File myObj = new File("filename.txt");
                                
                            //     if (myObj.createNewFile())
                            //     {
                            //       System.out.println("File created: " + myObj.getName());
                            //     } 
                            //     else
                            //     {
                            //       System.out.println("File already exists.");
                            //     }
                            // } 
                            // catch (IOException e)
                            // {
                            //     System.out.println("An error occurred.");
                            //     e.printStackTrace();
                            // }
                              
                            // try
                            // {
                            //     FileWriter fileWriter;
                            //     fileWriter = new FileWriter("filename.txt");
                            //     PrintWriter printWriter = new PrintWriter(fileWriter);
                            //     printWriter.print( jTextField3.getText());
                            //     printWriter.close();  
                            // }
                            // catch (IOException e) { e.printStackTrace(); }
                            
                            File myObj = new File("filename.txt");
                            FileWriter fileWriter;
                            fileWriter = new FileWriter(myObj);
                            PrintWriter printWriter = new PrintWriter(fileWriter);
                            printWriter.print( jTextField3.getText());
                            printWriter.close();  
                            
                        }
                        else
                        {
                            JFrame f = new JFrame();
                            JOptionPane.showMessageDialog( f, "We couldn't find your account.\n Please try again or register!" ); 
                        } 
                } catch( Exception e ) {  System.out.println( e ); }
            }
        }       
    });
        
        registerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                String name = jTextField5.getText();
                String email = jTextField6.getText();
                String userPassword = jTextField7.getText();
                
                String driver = "com.mysql.cj.jdbc.Driver";
                String url = "jdbc:mysql://34.69.74.87:3306/userdemo";
                String username = "root";
                String password = "20210406cp";
                
                if( evt.getSource() == registerButton )
                {
                    try
                    {
                        Class.forName(driver);
                        
                        java.sql.Connection conn2 = DriverManager.getConnection( url, username, password );
                        Statement statement2 = ((java.sql.Connection) conn2).createStatement();
                        String sql2 = "SELECT * FROM user WHERE username = '" + name + "'";
                        ResultSet results = statement2.executeQuery(sql2);
                        
                        java.sql.Connection conn3 = DriverManager.getConnection( url, username, password );
                        Statement statement3 = ((java.sql.Connection) conn3).createStatement();
                        String sql3 = "SELECT * FROM user WHERE password = '" + userPassword + "'";
                        ResultSet results2 = statement3.executeQuery(sql3);
                    
                        if ( results.next() && results2.next() )
                        {
                            
                            JFrame f = new JFrame();
                            JOptionPane.showMessageDialog( f, "You already have an account. Please login" );
                        }
                        else
                        {
                            if ( jTextField7.getText().equals( jTextField9.getText() ) )
                            {
                                if( jTextField6.getText().length() <= 10 || (  ( jTextField6.getText().length() > 10 ) && !jTextField6.getText().substring( jTextField6.getText().length() - 10, jTextField6.getText().length() ).equals( "@gmail.com" ) ) )
                                {
                                    JFrame jframe = new JFrame();
                                JOptionPane.showMessageDialog( jframe, "Invalid e-mail address. Please enter your mail address again\n Your e-mail address should be in the @gmail.com form " );
                                }
                            else {
                                try
                                {
                                    java.sql.Connection conn = DriverManager.getConnection( url, username, password );
                                    
                                    Statement state = ((java.sql.Connection) conn2).createStatement();
                                    String s = "INSERT INTO  user( username, password, email ) values('" + name + "', '" + userPassword + "', '" + email + "')";
                                    state.executeUpdate(s);
                                    
                                    Statement astatement1=((java.sql.Connection) conn).createStatement();
                                    String databaseName = name;
                                    String asql = new String(" create database " + databaseName ); 
                                    astatement1.executeUpdate(asql);
                                    
                                    String url2 = "jdbc:mysql://34.69.74.87:3306/" + databaseName;
                                    java.sql.Connection connectTable = DriverManager.getConnection( url2, username, password );
                                    
                                    Statement astatement2 = ((java.sql.Connection) connectTable).createStatement();
                                    String asql2 = "create table water (date varchar(100) not null, time varchar(50) not null," + 
                                                    "amount varchar(100) not null);";
                                    astatement2.executeUpdate(asql2);
                                    
                                    Statement astatement3 = ((java.sql.Connection) connectTable).createStatement();
                                    String asql3 = "create table energytracker (date varchar(100) not null, time varchar(50) not null," + 
                                                    "intake varchar(100) not null, consumption varchar(100) not null);";
                                    astatement3.executeUpdate(asql3);
                                    
                                    Statement astatement4 = ((java.sql.Connection) connectTable).createStatement();
                                    String asql4 = "create table activity (date varchar(100) not null, time varchar(50) not null," + 
                                                    "duration varchar(10) not null, activityname varchar(50) not null, calorie varchar(10) not null);";
                                    astatement4.executeUpdate(asql4);
                                    
                                    Statement astatement5 = ((java.sql.Connection) connectTable).createStatement();
                                    String asql5 = "create table food (date varchar(100) not null, time varchar(50) not null," + 
                                                    "foodname varchar(100) not null, grams varchar(100) not null, calorie varchar(100) not null);";
                                    astatement5.executeUpdate(asql5);
                                    
                                    astatement1.close();
                                    astatement2.close();
                                    astatement3.close();
                                    astatement4.close();
                                    astatement5.close();
                                    conn.close();
                                    
                                    // try {
                                    //     File myObj = new File("filename.txt");
                                    //     if (myObj.createNewFile()) {
                                    //       System.out.println("File created: " + myObj.getName());
                                    //     } else {
                                    //       System.out.println("File already exists.");
                                    //     }
                                    //   } catch (IOException e) {
                                    //     System.out.println("An error occurred.");
                                    //     e.printStackTrace();
                                    //   }
                                      
                                    // try {
                                    //     FileWriter fileWriter;
                                    //     fileWriter = new FileWriter("filename.txt");
                                    //     PrintWriter printWriter = new PrintWriter(fileWriter);
                                    //     printWriter.print( jTextField5.getText());
                                    //     printWriter.close();  
                                    // } catch (IOException e) {
                                    //     e.printStackTrace();
                                    // }
                                    
                                    File myObj = new File("filename.txt");
                                    FileWriter fileWriter;
                                    fileWriter = new FileWriter(myObj);
                                    PrintWriter printWriter = new PrintWriter(fileWriter);
                                    printWriter.print( jTextField5.getText());
                                    printWriter.close();  
                                    
                                    Registration reg = new Registration();
                                    reg.setVisible(true);
                                    setVisible(false);
                                    sendMail( jTextField6.getText() );
                                }
                                catch(Exception e) { e.printStackTrace(); }
                            }
                        }
                            else
                            {
                                JFrame f = new JFrame();
                                JOptionPane.showMessageDialog( f, "Please confirm your password correctly." );
                            }
                            
                            if( jTextField5.getText() ==  null || jTextField6.getText() ==  null || jTextField7.getText() ==  null || jTextField9.getText() ==  null )
                            {
                                JFrame anotherFrame = new JFrame();
                                JOptionPane.showMessageDialog( anotherFrame, "Please be sure that there is no missing information." );
                            }
                            
                            
                        }
                } catch( Exception e ) { e.printStackTrace(); }
            }
        }});

        registerButton.setText("Register");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(276, 276, 276)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel6))
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(607, 607, 607)
                            .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(206, 206, 206)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(108, 108, 108)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(78, 78, 78)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(254, 254, 254)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(257, 257, 257)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField5)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(registerButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>    
    
    public void sendMail( String recipient )
{
    Properties properties = new Properties();
    
    properties.put( "mail.smtp.auth", "true" );
    properties.put( "mail.smtp.starttls.enable", "true" );
    properties.put( "mail.smtp.host", "smtp.gmail.com" );
    properties.put( "mail.smtp.port", "587");
    properties.put( "mail.smtp.ssl.trust", "smtp.gmail.com" );
    properties.put( "mail.smtp.starttls.enable", "true" );
    
    
    String accountEmail = "aysemaksp@gmail.com";
    String password = "790106Abz*";
    
    Session session = Session.getInstance( properties, new Authenticator()
    {
        @Override
        protected PasswordAuthentication getPasswordAuthentication()
        {
            return new PasswordAuthentication( accountEmail, password );
        }
    });
    
    try
    {
        Message message = new MimeMessage( session );
        message.setFrom( new InternetAddress( accountEmail ));
        message.setRecipient( Message.RecipientType.TO, new InternetAddress( recipient ));
        message.setSubject( "Welcome to HealMeal! (Confirmation Mail)" );
        message.setText(" Welcome to HealMeal!\n" +  "We are glad to see you here.\n" + "Let's begin to explore the application!" );
        Transport.send(message); 
        System.out.println( "Message is sent successfully" );              
        
    } 
    catch (AddressException e)
    {
        e.printStackTrace();
    }
    catch (MessagingException e)
    {
        e.printStackTrace();
    }
}
                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new WelcomePage().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

                    
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField9;
    public javax.swing.JButton registerButton;
    BufferedImage image;
    // End of variables declaration                   
}
